apiVersion: v1
kind: Service
metadata:
  name: {{ template "flower.fullname" . }}
  labels:
    app: {{ template "flower.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.flower.port }}
      targetPort: {{ .Values.flower.port }}
  selector:
    app: {{ template "flower.fullname" . }}