# Default values for flower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mher/flower
  tag: latest

flower:
  port: 8888

redis:
  usePassword: false