apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "scheduler.fullname" . }}
  labels:
    app: {{ template "scheduler.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "scheduler.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.image.tag | quote }}
    spec:
      containers:
        - name: {{ template "scheduler.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{default "Always" .Values.pullPolicy}}
          command: {{ .Values.command }}
          env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host | default (printf "%s-redis" ( .Release.Name )) | quote }}