apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:802922962628:certificate/587e8d35-1cc3-4422-92b3-35a05f44df52
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  creationTimestamp: 2019-01-14T23:32:37Z
  labels:
    run: bountiesapi
  name: bountiesapi
  namespace: rinkebystaging
  resourceVersion: "417255"
  selfLink: /api/v1/namespaces/rinkebystaging/services/bountiesapi
  uid: ad7bab80-1854-11e9-98ce-02ec06901246
spec:
  clusterIP: 10.100.255.167
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30851
    port: 80
    protocol: TCP
    targetPort: 83
  - name: https
    nodePort: 30853
    port: 443
    protocol: TCP
    targetPort: 83
  selector:
    run: bountiesapi
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: aad7bab80185411e998ce02ec0690124-826059718.us-east-1.elb.amazonaws.com