# Default values for worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: consensysbounties/celery-playground
  tag: latest

command: '["bash", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]'

redis:
  usePassword: false

replicaCount: 1